version: '3.8'

services:
  react-app:
    build: .
    container_name: mirim_pay
    restart: always
    ports:
      - "${PORT:-2095}:${PORT:-2095}"
    volumes:
      - .:/app
    command: yarn dev --host --port 2095